<header>
            <a href="teacher_panel.php"><img class="logo" src="resources/logo.png" alt="logo"></a>
            <nav>
                <ul class="nav_link">
                    <li><a href="submit_code.php">Submit Code</a></li>
                    <li><a href="feedback.php">Feedback</a></li>
                    <li><a href="tasks.php">Tasks</a></li>

                    <button onclick="window.location.href='index.php'">Logout</button>
                </ul>
               
            </nav>
        </header>